global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.20.0.4:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.20.0.5:9100']

  - job_name: "jenkins"
    metrics_path: "/prometheus" 
    static_configs:
      - targets: ["172.20.0.2:8080"]    
