apiVersion: v1
kind: Service
metadata:
  name: api-devops
  labels:
    app: api-devops
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 32000
  selector:
    app: api-devops